### PR TITLE
Enhancement: Add PHP 7.0 and 7.1 to build matrix

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds PHP 7.0 and 7.1 to the Travis build matrix
* [x] requires `phpunit/phpunit:^4.5.0`

### CODE REVIEW

**Comment by localheinz** [comment]
Build is failing because Travis installs `phpunit/phpunit:^6` on PHP 7.0 and 7.1 - shall we require `phpunit/phpunit:^4.5.0` as a development dependency?

**Comment by glaubinix** [comment]
@localheinz yes, please.

**Comment by localheinz** [comment]
@glaubinix 

Not sure why yet, but following #25, the build is broken, see https://travis-ci.org/breerly/factory-girl-php/builds/237506444. Looking into it.

**Comment by localheinz** [comment]
Thank you, @glaubinix!

**Pull request merged**
