### PR TITLE
Fix: Test against highest and lowest versions of dependencies

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] removes and ignores `composer.lock`, and tests against highest and lowest versions of dependencies

💁‍♂️ The primary reason for this is that I would like to bump [these requirements](https://github.com/breerly/factory-girl-php/blob/04e384294149a2ad9e69961f3d99058f8d9ab409/composer.json#L26-L28) up.

### CODE REVIEW

**Comment by glaubinix** [comment]
@localheinz as far as I can see we currently support up to the latest doctrine version and I haven't seen anything which would require us to drop a certain version. Something which I would also like to avoid before actually tagging a v1.0. Do you mind elaborating what your idea behind the version bump is?

I figured changing the requirements would be necessary once doctrine3 is released (in combination with dropping all pre php 7/7.1 support).

**Comment by localheinz** [comment]
@glaubinix 

Was thinking about raising the upper bound for [`doctrine/common`](https://github.com/breerly/factory-girl-php/blob/04e384294149a2ad9e69961f3d99058f8d9ab409/composer.json#L28), specifically!

For reference, see https://github.com/doctrine/common/compare/v2.6.1...v2.7.2.

**Comment by glaubinix** [comment]
I also set doctrine/common to <2.8-dev and will tag this as 1.0.

**Comment by localheinz** [comment]
Very nice, @glaubinix! Thank you!

**Pull request merged**
